baseURL = "https://coderdojo-schoeneweide.github.io/"
languageCode = "de-de"
title = "CoderDojo Sch√∂neweide"
theme = "coderdojoschoeneweide"

[[menu.main]]
  identifier = "datenschutz"
  name = "Datenschutz"
  url = "/datenschutz/"
  weight = 4
